#!/usr/bin/env bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Export the tree under test and generate the harness crate. run.sh calls this whenever the
# sources changed; there is no need to run it by hand.
#
#   variants/yaspar-ir/   yaspar-ir @ $IR_CUR_REV, plus the entry-point shims (inject_shims.py)
#   variants/macros/      yaspar-macros @ $MACROS_REV, when MACROS_REPO is set
#   runs/harness/         a crate compiling harness/ against variants/yaspar-ir
#
# Sources are exported with `git archive` (uncommitted changes via `git stash create`, which
# touches no ref and no file), so the repositories are never modified; the revisions are
# recorded in variants/REVISIONS.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
source ./config.sh

export_tree() { # repo rev dest
    rm -rf "$3"
    mkdir -p "$3"
    git -C "$1" archive "$2" | tar -x -C "$3"
}

if [[ $IR_CUR_REV == WORKTREE ]]; then
    CUR_SHA=$(git -C "$IR_REPO" stash create)
    [[ -n $CUR_SHA ]] || CUR_SHA=$(git -C "$IR_REPO" rev-parse HEAD)
else
    CUR_SHA=$(git -C "$IR_REPO" rev-parse "$IR_CUR_REV")
fi
MAC_SHA=
if [[ -n $MACROS_REPO ]]; then
    MAC_SHA=$(git -C "$MACROS_REPO" rev-parse "$MACROS_REV")
    if [[ -n "$(git -C "$MACROS_REPO" status --porcelain --untracked-files=no)" ]]; then
        echo "note: $MACROS_REPO has uncommitted changes; they are NOT part of the export ($MAC_SHA)" >&2
    fi
fi

# runs/harness/target is kept: rebuilding cvc5 from nothing takes a quarter of an hour.
rm -rf variants
mkdir -p variants runs/harness
export_tree "$IR_REPO" "$CUR_SHA" variants/yaspar-ir
if [[ -n $MACROS_REPO ]]; then export_tree "$MACROS_REPO" "$MAC_SHA" variants/macros; fi
python3 scripts/inject_shims.py variants/yaspar-ir

cat > variants/REVISIONS <<EOF
yaspar-ir            $CUR_SHA ($IR_CUR_REV)
yaspar-macros        ${MAC_SHA:-as resolved from Cargo.toml} (${MACROS_REPO:-crates.io})
generated            $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
cat variants/REVISIONS

d=runs/harness
cat > "$d/Cargo.toml" <<EOF
# Generated by setup.sh -- do not edit; edit setup.sh.
[package]
name = "ssbench"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "../../harness/src/lib.rs"
bench = false

# the same entry point twice: criterion runs the bench, the coverage run the binary
[[bin]]
name = "ssbench"
path = "../../harness/src/main.rs"

[[bench]]
name = "stack_safe"
path = "../../harness/benches/stack_safe.rs"
harness = false

[features]
cvc5 = ["dep:cvc5", "yaspar-ir/cvc5"]

[dependencies]
yaspar-ir = { path = "../../variants/yaspar-ir", default-features = false, features = ["all"] }
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
regex = "1"
dashu = "0.4.2"
cvc5 = { version = "0.5.1", optional = true }
EOF
if [[ -n $MACROS_REPO ]]; then
    cat >> "$d/Cargo.toml" <<EOF

[patch.crates-io]
yaspar-macros = { path = "../../variants/macros" }
yaspar-macros-defs = { path = "../../variants/macros/defs" }
EOF
fi
cat >> "$d/Cargo.toml" <<EOF

# One codegen unit, so that inlining decisions do not depend on how the crate was partitioned.
[profile.release]
opt-level = 3
debug = false
codegen-units = 1
incremental = false

[profile.bench]
inherits = "release"

[workspace]
EOF

# A lockfile that still pins another yaspar-macros would make cargo ignore the [patch] above (it
# only warns), so the lockfile is rebuilt whenever the macros source changes.
if [[ "$(cat "$d/.macros" 2>/dev/null)" != "$MAC_SHA" ]]; then
    rm -f "$d/Cargo.lock"
fi
if [[ -z $MACROS_REPO && ! -f "$d/Cargo.lock" && -f "$IR_REPO/Cargo.lock" ]]; then
    cp "$IR_REPO/Cargo.lock" "$d/Cargo.lock"
fi
echo "$MAC_SHA" > "$d/.macros"

resolved=$(cargo tree --manifest-path "$d/Cargo.toml" -i yaspar-macros --depth 0 2>/dev/null | head -1)
if [[ -n $MACROS_REPO && $resolved != *"variants/macros"* ]]; then
    echo "runs/harness resolves '$resolved', not the checkout in variants/macros" >&2
    exit 1
fi
echo "== $resolved"
fingerprint > variants/FINGERPRINT
echo "setup done"
