name: Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check

      - name: Run copyright check
        run: |
          ./.github/copyright-check.sh src
          ./.github/copyright-check.sh tests

  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        rust: [ stable ]
        features:
          - 'none'
          - 'cnf'
          - 'implicant-generation'
          - 'all'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --no-default-features --features "${{ matrix.features }}"

  test-cvc5:
    name: Test Suite (cvc5)
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cvc5
        id: cvc5
        uses: ./.github/actions/setup-cvc5

      - uses: Swatinem/rust-cache@v2

      - name: Run cvc5 tests
        run: cargo test --features cvc5
        env:
          CVC5_DIR: ${{ steps.cvc5.outputs.cvc5-dir }}

  regression:
    name: Regression Tests
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup cvc5
        id: cvc5
        uses: ./.github/actions/setup-cvc5
      - uses: Swatinem/rust-cache@v2
      - name: Run regression tests
        run: cargo test --release --features regression --test regression
        env:
          CVC5_DIR: ${{ steps.cvc5.outputs.cvc5-dir }}

  lints:
    name: Lints
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup cvc5
        id: cvc5
        uses: ./.github/actions/setup-cvc5

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-features --tests -- -D warnings
        env:
          CVC5_DIR: ${{ steps.cvc5.outputs.cvc5-dir }}

      - name: Run rustdoc lints
        run: cargo doc --workspace --all-features --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: ""
          CVC5_DIR: ${{ steps.cvc5.outputs.cvc5-dir }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cvc5
        id: cvc5
        uses: ./.github/actions/setup-cvc5

      - name: Build documentation
        run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
          CVC5_DIR: ${{ steps.cvc5.outputs.cvc5-dir }}
